services:
  newfavoritechild:
    build: .
    container_name: newfavoritechild
    ports:
      - "5003:5003"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - DATABASE_PATH=/app/data/newfavoritechild.db
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
